# Site settings
title: Jacob Konikoff
email: "jkoniko1 <em>flyingbison</em> jhu.edu (flyingbison=@)"
description: > # this means to ignore newlines until "baseurl:"
  Personal academic website of Jacob Konikoff 
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  jacobkonikoff
exclude: ['README.md']

# Build settings
markdown: kramdown
